### PR TITLE
#17 Type casting to type checking

### PR DESCRIPTION
**Pull request by eddiejaoude**

### CODE REVIEW

**Comment by eddiejaoude** [comment]
@fantasticjamieburns @knasher please review

**Comment by fantasticjamieburns** [comment]
I normally try to put the variable name on the exception to make it more obvious if this appears in a log etc.

**Comment by fantasticjamieburns** [comment]
But it's good stuff.

**Comment by eddiejaoude** [comment]
> I normally try to put the variable name on the exception to make it more obvious if this appears in a log etc.

Sounds like a good idea. Is that something we can do at a later stage & get this in now? Otherwise it will become stale.

**Pull request merged**
